name: boarding
version: 0.2.4
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: A package for board games or canvas drawings. The package has both model and view libraries. See the example folder to see how to use the boarding package.
homepage: https://github.com/dzenanr/boarding
environment:
  sdk: '>=1.8.0 <2.0.0'
documentation: http://goo.gl/kXlDOJ
dependencies:
  browser: '>=0.10.0+2 <1.0.0'
  dartling: '>=1.0.6 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.3 <1.0.0'
